version: '3.3'

services:
  #service 1: definition of mssql database
  dbi431200_goglobal:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-db
    environment:
      - SA_PASSWORD=TimK2002Docker
      - ACCEPT_EULA=Y
    ports:
      - "3306:3306"
    restart: always

  #service 3: definition of your spring-boot app
  goglobal-application:                   #it is just a name, which will be used only in this file.
    image: goglobal-application-app           #name of the image after dockerfile executes
    container_name: goglobal-backend      #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "4000:8080"                       #docker container port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - dbi431200_goglobal                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql.fhict.local;database=dbi431200_goglobal
      SPRING_DATASOURCE_USERNAME: dbi431200_goglobal
      SPRING_DATASOURCE_PASSWORD: GoGlobalPW

